backend:
  # Use netlify identity as backend
  name: "git-gateway"
  branch: "main"
  repo: "https://github.com/AXYS-Creative/joinsunder.git" # CHANGE ME
media_folder: "src/static/img"
public_folder: "/static/img"
site_url: https://joinsunder-cms.netlify.app # CHANGE ME # On admin login page, this adds a 'go back to site' link. Also added in the corner when logged in.
display_url: https://joinsunder-cms.netlify.app # CHANGE ME # In admin dashboard, this addes the URL in the corner. Used with 'preview_path' for collection viewing.
logo_url: https://joinsunder-cms.netlify.app/static/img/admin-logo.svg # CHANGE ME # On admin login page, this adds a custom logo.

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - name: "home_page"
    label: "Page - Home"
    description: >
      Edit the content for joinsunder.com
      Have questions or need a new config? Visit your Trello board to add a new request.
      https://trello.com/b/l897wwEP/join-sunder. You can also reach us at help@axyscreative.com
    files:
      - name: "hero_section"
        label: "Hero Section"
        file: "src/_data/page_home.yaml"
        preview_path: "/"
        editor:
          preview: false
        fields:
          - name: "hero_text"
            label: "Hero Text"
            widget: "string"
            required: true
          - name: "video_embed"
            label: "Video Embed"
            widget: "string"
            required: true
            hint: "Paste <iframe> embed here. Go to the youtube video, click 'share', then embed. Copy the iframe content and paste here."
          - name: "img_reel"
            label: "Image Reel"
            label_singular: "Image"
            widget: "list"
            collapsed: false
            required: true
            max: 22
            fields:
              - {
                  name: "src",
                  label: "Image Source",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "alt",
                  label: "Image Description",
                  widget: "string",
                  required: true,
                  hint: "For accessibility. Describe the image while avoiding these words: image, photo, picture, etc.",
                }
  - name: "compete_page"
    label: "Page - Compete"
    files:
      - name: "hero_section"
        label: "Hero Section - Video Library"
        file: "src/_data/page_compete.yaml"
        preview_path: "/compete"
        editor:
          preview: false
        fields:
          - name: "page_heading"
            label: "Page Heading"
            widget: string
            required: true
            hint: Semantic page heading for accessibility. Not visually shown on the page (per design) but improves indexing and other areas.
          - name: "video_library"
            label: "Video Library"
            label_singular: "Video"
            widget: "list"
            collapsed: true
            required: true
            fields:
              - {
                  name: "title",
                  label: "Title",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "sub_title",
                  label: "Subtitle",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "poster",
                  label: "Poster",
                  widget: "image",
                  required: true,
                  hint: Thumbnail shown on the video library carousel,
                }
              - {
                  name: "embed",
                  label: "Embed",
                  widget: "string",
                  required: true,
                  hint: "Paste <iframe> embed here. Go to the youtube video, click 'share', then embed. Copy the iframe content and paste here.",
                }
  - name: "experience_page"
    label: "Page - Experience"
    files:
      - name: "hero_section"
        label: "Hero Section - Image Reel"
        file: "src/_data/page_experience_images.yaml"
        preview_path: "/experience"
        editor:
          preview: false
        fields:
          - name: "page_heading"
            label: "Page Heading"
            widget: string
            required: true
            hint: Semantic page heading for accessibility. Not visually shown on the page (per design) but improves site scraping.
          - name: "img_reel_1"
            label: "Image Reel 1"
            label_singular: "Image"
            widget: "list"
            collapsed: true
            required: true
            fields:
              - {
                  name: "src",
                  label: "Image Source",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "alt",
                  label: "Image Description",
                  widget: "string",
                  required: true,
                  hint: "For accessibility. Describe the image while avoiding these words: image, photo, picture, etc.",
                }
          - name: "img_reel_2"
            label: "Image Reel 2"
            label_singular: "Image"
            widget: "list"
            collapsed: true
            required: true
            fields:
              - {
                  name: "src",
                  label: "Image Source",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "alt",
                  label: "Image Description",
                  widget: "string",
                  required: true,
                  hint: "For accessibility. Describe the image while avoiding these words: image, photo, picture, etc.",
                }
          - name: "img_reel_3"
            label: "Image Reel 3"
            label_singular: "Image"
            widget: "list"
            collapsed: true
            required: true
            fields:
              - {
                  name: "src",
                  label: "Image Source",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "alt",
                  label: "Image Description",
                  widget: "string",
                  required: true,
                  hint: "For accessibility. Describe the image while avoiding these words: image, photo, picture, etc.",
                }
          - name: "img_reel_4"
            label: "Image Reel 4"
            label_singular: "Image"
            widget: "list"
            collapsed: true
            required: true
            fields:
              - {
                  name: "src",
                  label: "Image Source",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "alt",
                  label: "Image Description",
                  widget: "string",
                  required: true,
                  hint: "For accessibility. Describe the image while avoiding these words: image, photo, picture, etc.",
                }
      - name: "video_library"
        label: "Video Library"
        file: "src/_data/page_experience_videos.yaml"
        preview_path: "/experience#video-library"
        editor:
          preview: false
        fields:
          - name: "video_library"
            label: "Video Library"
            label_singular: "Video"
            widget: "list"
            collapsed: true
            required: true
            fields:
              - {
                  name: "title",
                  label: "Title",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "sub_title",
                  label: "Subtitle",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "poster",
                  label: "Poster",
                  widget: "image",
                  required: true,
                  hint: Thumbnail shown on the video library carousel,
                }
              - {
                  name: "embed",
                  label: "Embed",
                  widget: "string",
                  required: true,
                  hint: "Paste <iframe> embed here. Go to the youtube video, click 'share', then embed. Copy the iframe content and paste here.",
                }
  - name: "resources_page"
    label: "Page - Resources"
    files:
      - name: "hero_section"
        label: "Hero Section"
        file: "src/_data/page_resources_hero.yaml"
        preview_path: "/resources"
        editor:
          preview: false
        fields:
          - name: "heading"
            label: "Heading"
            widget: string
            required: true
          - name: "subheading"
            label: "Sub Heading"
            widget: object
            required: true
            fields:
              - {
                  name: "static_text",
                  label: "Static Text",
                  widget: "string",
                  required: true,
                  hint: This text won't animate on scroll,
                }
              - {
                  name: "floating_text_1",
                  label: "Floating Text 1",
                  widget: string,
                  required: false,
                  hint: The first text to animate on scroll,
                }
              - {
                  name: "floating_text_2",
                  label: "Floating Text 2",
                  widget: string,
                  required: false,
                  hint: The second text to animate on scroll,
                }
          - name: "hero_images"
            label: "Hero Images"
            label_singular: "Image"
            widget: "list"
            collapsed: true
            allow_add: true
            min: 3
            max: 3
            required: true
            fields:
              - {
                  name: "src",
                  label: "Image Source",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "alt",
                  label: "Image Description",
                  widget: "string",
                  required: true,
                  hint: "For accessibility. Describe the image while avoiding these words: image, photo, picture, etc.",
                }
      - name: "team_portraits"
        label: "Team Portraits"
        file: "src/_data/page_resources_team.yaml"
        preview_path: "/experience#team-portraits"
        editor:
          preview: false
        fields:
          - name: "portraits"
            label: "Portraits"
            label_singular: "Portrait"
            widget: "list"
            collapsed: true
            required: true
            fields:
              - {
                  name: "name",
                  label: "Name",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "role",
                  label: "Role",
                  widget: "string",
                  required: true,
                }
              - { name: "src", label: "Image", widget: "image", required: true }
  - name: "global_components"
    label: "Global Components"
    description: >
      Global site content, such as the primary navigation.
    files:
      - name: "navigation"
        label: "Navigation"
        file: "src/_data/navigation.yaml"
        preview_path: "/"
        editor:
          preview: false
        fields:
          - name: "nav_links"
            label: "Nav Links"
            widget: "list"
            allow_add: false
            min: 6
            max: 6
            collapsed: true
            required: true
            fields:
              - {
                  name: "title",
                  label: "Link Title",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "desktop_image",
                  label: "Desktop Image",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "mobile_image",
                  label: "Mobile Image",
                  widget: "image",
                  required: true,
                }
      - name: "page_loader"
        label: "Page Loader"
        file: "src/_data/loader.yaml"
        preview_path: "/"
        editor:
          preview: false
        fields:
          - name: "loader_toggle"
            label: "Loader Toggle"
            widget: "boolean"
            default: true
          - name: "loader_text"
            label: "Loader Text"
            widget: "string"
            required: true
            hint: 'Wrap individual words in this convention to animate them: <span class="page-loader__block">Empower</span>'
      - name: "video_carousel"
        label: "Video Carousel"
        file: "src/_data/video_carousel.yaml"
        preview_path: "/compete"
        editor:
          preview: false
        fields:
          - name: "play_icon"
            label: "Play Icon"
            widget: image
            required: false
            hint: Corner icon for each video poster. Leave this field empty to remove the icon.
  - name: "meta_data"
    label: "Meta Data"
    description: >
      Edit the meta data for joinsunder.com.
    files:
      - name: "meta_data"
        label: "Meta Data"
        file: "src/_data/meta_data.yaml"
        editor:
          preview: false
        fields:
          - name: "site_name"
            label: "Site Name"
            widget: "string"
            required: true
            hint: "Sample Business Co"
          - name: "url"
            label: "URL"
            widget: "string"
            required: true
            hint: "Full URL to your site"
          - name: "author"
            label: "Author"
            widget: "string"
            required: true
            hint: "Person or company name"
          - name: "contact_email"
            label: "Contact Email"
            widget: "string"
            required: true
            hint: "Email address for rich results schema"
          - name: "theme_color"
            label: "Theme Color"
            widget: "color"
            required: true
            hint: "Hex color code for overflow color on some devices"
          - name: "og_title"
            label: "Open Graph Title"
            widget: "string"
            required: true
            hint: "Sample Business | Motto here"
          - name: "og_description"
            label: "Open Graph Description"
            widget: "string"
            required: true
            hint: "Keep at least 100 characters"
          - name: "og_image"
            label: "Open Graph Image"
            widget: "image"
            default: "https://joinsunder-cms.netlify.app/static/img/og-image.png"
            required: true
            hint: "Recommended formats: PNG or JPG. Recommended image dimensions: 1200 x 630 pixels. File size should be under 8 MB."
