backend:
  # Use netlify identity as backend
  name: "git-gateway"
  branch: "main"
  repo: "https://github.com/AXYS-Creative/joinsunder.git" # CHANGE ME
media_folder: "src/static/img"
public_folder: "/static/img"
site_url: https://joinsunder-cms.netlify.app # CHANGE ME # On admin login page, this adds a 'go back to site' link. Also added in the corner when logged in.
display_url: https://joinsunder-cms.netlify.app # CHANGE ME # In admin dashboard, this addes the URL in the corner. Used with 'preview_path' for collection viewing.
logo_url: https://joinsunder-cms.netlify.app/static/img/admin-logo.svg # CHANGE ME # On admin login page, this adds a custom logo.

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - name: "home_page"
    label: "Page - Home"
    description: >
      Edit the site content here.
      Have questions or need to add a new config? Visit your Trello board to add a new request.
      Don't have a Trello board? Reach out to Aaron or Bailey → help@axyscreative.com
    files:
      - name: "marquee"
        label: "Marquee"
        file: "src/_data/marquee.yaml"
        preview_path: "#"
        editor:
          preview: false
        fields:
          - name: "marquee_toggle"
            label: "Marquee Toggle"
            widget: "boolean"
            hint: "Hide or show the discount marquee."
          - name: "marquee_text"
            label: "Marquee Text"
            required: true
          - name: "marquee_text_speech"
            label: "Marquee Text Speech"
            widget: "string"
            hint: "For accessibility, add your message here without any symbols, tokens or classes."
            required: true
  - name: "meta_data"
    label: "Meta Data"
    description: >
      Edit the site's meta data here. Open Graph dimensions: 1200x630. Open graph file name: open-graph.png
    files:
      - name: "meta_data"
        label: "Meta Data"
        file: "src/_data/meta_data.yaml"
        editor:
          preview: false
        fields:
          - name: "author"
            label: "Author"
            widget: "string"
            required: true
            hint: "Person or company name"
          - name: "contact_email"
            label: "Contact Email"
            widget: "string"
            required: true
            hint: "Email address for rich results schema"
          - name: "theme_color"
            label: "Theme Color"
            widget: "color"
            required: true
            hint: "Hex color code for overflow color on some devices"
          - name: "url"
            label: "URL"
            widget: "string"
            required: true
            hint: "Full URL to your site"
          - name: "og_title"
            label: "Open Graph Title"
            widget: "string"
            required: true
            hint: "Sample Business | Motto here"
          - name: "og_description"
            label: "Open Graph Description"
            widget: "string"
            required: true
            hint: "Keep at least 100 characters"
          - name: "og_img"
            label: "Open Graph Image"
            widget: "string"
            required: true
            hint: "https://sample.com/static/img/open-graph.png"
          - name: "site_name"
            label: "Site Name"
            widget: "string"
            required: true
            hint: "Sample Business Co"
